### ISSUE TITLE
How to set the 'download folder' for JkDependencyResolver  (local JkRepo path) ? 

### ISSUE THREAD

**Issue by ChrWeissDe** [jeka-dev/jeka#234]
I have more a question - and I hope that you can help me as I haven't found the answer in the docs. 

I am using following code to resolve and download artifacts: 

```
JkDependencySet deps =  JkDependencySet.of().and("org.apache.poi:poi-ooxml:5.1.0").and("org.apache.poi:poi:5.1.0");		JkDependencyResolver resolver = JkDependencyResolver.of();
resolver.addRepos(JkRepo.ofMavenCentral());
List<Path> libs = resolver.resolve(deps).getFiles().getEntries();
```

So far - so good and I see that the files are download to the JKRep (?) loc:  C:\Users\....\.jeka\cache\repo 

However how can I modify this location? Is there any parameter? Or can I easily add it to the code snipplet below ? 
Any help is appreciated. Thanks

**Comment by djeang** [comment]
Hi, 

You can change this location using an environment variable as mentioned [here](https://jeka-dev.github.io/jeka/reference-guide/execution-engine-setup/#customization).

Hope it helps

**Comment by ChrWeissDe** [comment]
@djeang: thanks a lot for your quick help! Works like a charme.
