### ISSUE TITLE
[Question] JkDependencyResolver; Jekahow to set repo url for downloading the required ivy.jar package? 

### ISSUE THREAD

**Issue by ChrWeissDe** [jeka-dev/jeka#235]
Hi, 

I am using the JKDependencyResolver and oberserved that the JK classes downloads  ivy.jar package as an own requirement / 'prerequisite' (during the resolve process). 

However - here I have the challenge that I need to pass a own url to an own Nexus server ; as I need to run the code behind a company firewall. 
Is there any easy way to do this? What would I need to change? 

Any help is more than appreciated. 

Thanks upfront.

**Comment by ChrWeissDe** [comment]
Just seeing in dev.jeka.core.api.depmanagement.resolution.JkInternalDependencyResolver:

            JkUrlFileProxy fileProxyIvy = JkUrlFileProxy.of(
                    "https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0/ivy-2.5.0.jar",
                    JkCoordinate.of("org.apache.ivy:ivy:2.5.0").cachePath());
            IVY_CLASSLOADER = JkInternalEmbeddedClassloader.ofMainEmbeddedLibs(fileProxyIvy.get());
            return IVY_CLASSLOADER;

`Thus I guess there is no way to dynamically configure the repo - right?

**Comment by djeang** [comment]
Right !

I can make a fix to be able to configure the base url (https://repo1.maven.org/maven2) by passing a system property as `jeka.repos.download=https://my.company/repo`.

Would it be a good solution for your problem ?

**Comment by ChrWeissDe** [comment]
Hi @djeang, 

Thanks for your reply - yes that would be great! 
And as mentioned before: I think this would be a great improvement as it allows then to run jeka behind any firewall / proxy.

**Comment by djeang** [comment]
This has been released in 0.10.12.
You can reopen this issue if this does not match your expectations.
