### ISSUE TITLE
SonarQube and JaCoCo plugins status

### ISSUE THREAD

**Issue by amottier** [jeka-dev/jeka#237]
I was wondering what is the current status of SonarQube and JaCoCo plugins?

From this [comment](https://github.com/jeka-dev/jeka/issues/181#issuecomment-938572310) I understand that https://github.com/jeka-dev/jeka/tree/master/plugins/dev.jeka.plugins.sonarqube and https://github.com/jeka-dev/jeka/tree/master/plugins/dev.jeka.plugins.jacoco should not be used (and actually I would expect them to no longer exist according to comment) and that instead, I should use https://github.com/jerkar/sonarqube-plugin and https://github.com/jerkar/jacoco-plugin but both repositories are archived.

So I was wondering if a maintained version of those plugins still exist?

Thanks a lot.

**Comment by djeang** [comment]
Hi Antoine,`
Both Sonarqube and Jacoco plugin has moved to Jeka 'mono' repo, here :  https://github.com/jeka-dev/jeka/tree/master/plugins/dev.jeka.plugins.sonarqube and https://github.com/jeka-dev/jeka/tree/master/plugins/dev.jeka.plugins.jacoco
This has improved consistency and eased release management.
The archived repos has been so on purpose, you can skip them.
Kind Regards



 
 
 


I was wondering what is the current status of SonarQube and JaCoCo plugins?

From this comment I understand that https://github.com/jeka-dev/jeka/tree/master/plugins/dev.jeka.plugins.sonarqube and jeka/plugins/dev.jeka.plugins.jacoco at master · jeka-dev/jeka should not be used (and actually I would expect them to no longer exist according to comment) and that instead, I should use https://github.com/jerkar/sonarqube-plugin and https://github.com/jerkar/jacoco-plugin but both repositories are archived.


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
jeka/plugins/dev.jeka.plugins.jacoco at master · jeka-dev/jeka

The DevOps Backbone for JVM. Contribute to jeka-dev/jeka development by creating an account on GitHub.
 |

 |

 |




So I was wondering if a maintained version of those plugins still exist?

Thanks a lot.

**Comment by amottier** [comment]
Thanks for the clarification @djeang 

This [comment](https://github.com/jeka-dev/jeka/issues/181#issuecomment-938572310) let me believe that I should not use the JaCoCo and SonarQube plugin from the mono repo but I was wrong :slightly_smiling_face: 

I'll try to run the plugins from the mono repo but first I need to solve #238.
