### ISSUE TITLE
Building Jeka (including wrapper) from sources without IntelliJ (e.g. on a CI)

### ISSUE THREAD

**Issue by amottier** [jeka-dev/jeka#238]
I'm trying to build Jeka using GitLab CI. I have no problem running the Ant script that bootstraps the build, based on the [documentation](https://github.com/jeka-dev/jeka/tree/master#build-jeka-from-command-line), but I can't figure out from there how to launch a Jeka build with Jeka on the command line (without using an IDE) and then get a working Jeka wrapper.

Any help would be greatly appreciated.

Thanks

**Comment by djeang** [comment]
Hi, 

I don't really understand what you are intenting to do. The Ant scripts just compiles the Jeka sources code, then run the compiled code, to build JeKa itself. We don't need to have a JeKa Wrapper, to build JeKa. 
If tthe CI cannot run ANT, then we need to write an shell script that does the same thing than the Ant file. It should not be to hard.

Kind Regards
