### ISSUE TITLE
Jeka equivalent of mvn

### ISSUE THREAD

**Issue by cowwoc** [jeka-dev/jeka#240]
Consider adding a command-line script like mvn that installs Jeka, if needed, before building the project in the current directory.

**Comment by cowwoc** [comment]
I see you already have a "wrapper" util to do this. This is probably more of a documentation task than anything else. It isn't clear from the documentation how to add one to your project.

**Comment by djeang** [comment]
How did you get into JeKa ?  Command line ?
If you go using IntelliJ plugin (the recommended way), it creates a wrapper by default.
