### ISSUE TITLE
[Qustion] How to add Jeka to an existing Gradle project, and does Jeka have shadow plugin?

### ISSUE THREAD

**Issue by kappa-maintainer** [jeka-dev/jeka#241]
Copying files from a new Jeka project created from plugin to a Gradle projects seems not working? It just can't sync

**Comment by djeang** [comment]
You can not add jeka on the same base directory than a Gradle or Maven project as dependency resolution an IDE metadata will collide.
As a workaround, you can setup JeKa base dir in a sub-dir of your gradle project. For example :

```
my_project
 |-gradlew.bat
 |-...
 |-jeka-module
       |-jekaw.bat
       |-jeka
            |-def 
            |- ...
```
[See](https://jeka-dev.github.io/jeka/faq/#how-can-i-use-maven-or-gradle-in-conjunction-with-jeka-in-intellij)

**Comment by djeang** [comment]
For the last version of Jeka,, you can refer to FAQ https://jeka-dev.github.io/jeka/faq/#how-can-i-use-mavengradle-in-conjunction-with-jeka. 
If needed, I can add a convenient method to do this from IntelliJ plugin, in one click. Would it make sense to you ?

**Comment by djeang** [comment]
About Shadow jar, there is currently no support for it. You can only produce unshadowed fat-jar. Support for shadow jar should be included in the future but it seems to not be trivial concern.

**Comment by kappa-maintainer** [comment]
That's all I want to know, thanks

**Comment by djeang** [comment]
Now, it can.

Super easy : https://jeka-dev.github.io/jeka/tutorials/build-projects/#configure-jar-type

**Comment by djeang** [comment]
For coexisting with Maven/Gradle. There is now a better way : https://jeka-dev.github.io/jeka/faq/#how-can-i-use-mavengradle-in-conjunction-with-jeka
