### ISSUE TITLE
Kotlin example

### ISSUE THREAD

**Issue by tokazio** [jeka-dev/jeka#244]
How do you configure jeka to compile kotlin code please ?

(and how about using kapt or ksp annotation processors ?)

**Comment by djeang** [comment]
Hi,

You can find an example [here](https://github.com/jeka-dev/working-examples/tree/master/springboot-kotlin-reactjs). 

About kapt and ksp, there is currently no support out-of-the-box. This may change if users ask for (or contribute to).

However the example show, how you can add plugins and plugin options to Kotlin compiler : https://github.com/jeka-dev/working-examples/blob/master/springboot-kotlin-reactjs/jeka-src/Build.kt

Hope it helps

**Comment by djeang** [comment]
Hi,

Is it fine for you, now ? Can we close the issue or do you need more support for this issue ?

**Comment by tokazio** [comment]
Oh sorry, it's ok ! Thanks 
You can close.
